#!/bin/bash -e

read -p "This will deploy your branch to production docker servers, are you sure you want to do this? [y/N] " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

echo "Deploying to production docker hosts"
git branch -f deploy-docker
git push -f origin deploy-docker
make deploy-docker
