#!/bin/bash 

set -e

SCRIPT_NAME=$BASH_SOURCE
if [ -h $SCRIPT_NAME ]; then SCRIPT_NAME=$(readlink $SCRIPT_NAME); fi

cd `dirname $SCRIPT_NAME`

redis() {
    local TARGET=$1
    shift
    
    $(./cli.js -s $TARGET --print) "$@"
}

USER=$1
PROJECT=$2
TARGET=${3:-devel}

USER_ID=$(redis $TARGET hget u/unames $USER)
echo $(redis $TARGET hget u/$USER_ID/pnames $PROJECT)


