// For more information see http://docs.c9.io:8080/#!/api/run-method-run
// put me in .c9/runners/
{
  "cmd": [
    "sh",
    "-c",
    "/usr/bin/make $file_base_name && gdbserver :15470 $file_path/$file_base_name $args"
  ],

  "info": "Compiling $file ...",
  "debugport": 15470,
  "debugger": "gdb",
  "executable": "$file_path/$file_base_name",
  "maxdepth": 50,
  "env": {},
  "selector": "^.*\\.c$"
}