{
    "cmd": [
        "`if ! which php &>/dev/null || php --version | grep -qE ' [0-4]\\.| 5\\.[0-3]'; then echo Please install PHP 5.4 or later for this feature >&2; echo :; else echo php; fi`",
        "-S",
        "$IP:$PORT"
    ],
    "selector": "^.*\\.(php|phtml|html|shtml)$",
    "info": "Starting PHP built-in web server, serving \\033[01;34m$hostname_path\\033[00m.",
    "cwd": "$project_path"
}
